name: Build ThunderLibraries on Linux

on:
  push:
    # branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:

jobs:
  Thunder:
    uses: rdkcentral/Thunder/.github/workflows/Build Thunder on Linux.yml@master

  ThunderLibraries:
    needs: Thunder
    uses: VeithMetro/ThunderLibraries/.github/workflows/Linux build template.yml@development/actions
