name: Build ThunderLibraries on Linux

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Thunder:
    uses: VeithMetro/Thunder/.github/workflows/Linux build template.yml@development/actions

  ThunderLibraries:
    needs: Thunder
    uses: VeithMetro/ThunderLibraries/.github/workflows/Linux build template.yml@development/actions
